# Generated by Django 4.0.6 on 2022-07-14 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_images_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='images_post',
        ),
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
